### PR TITLE
Fixed murmur installation

### PR DESCRIPTION
**Pull request by zovt**

### CODE REVIEW

**Comment by feralhosting** [comment]
~~~
echo -e "export LD_LIBRARY_PATH=~/murmur/usr/lib/x86_64-linux-gnu:/usr/lib" >> ~/.bash_profile
source ~/.bash_profile
~~~
**1:**  can you please use the `~/.bashrc` file
**2:** I am not sure sourcing will work from the subshell the script is running for when they exit back to their main shell.

**Comment by zovt** [comment]
Regarding point 1: Sure!

Regarding point 2: Yeah, I'm not sure either. I think it _should_. I guess it could just run the export command directly in the script.

**Comment by feralhosting** [comment]
you can note it in the script as a closing comment or refer them back to the FAQ from the script.

~~~
echo "Please run this command: source ~/.bashrc
echo
echo "Please now return to the FAQ to complete the setup
echo
exit
~~~

**Comment by zovt** [comment]
Cool, thanks.

**Pull request merged**
