### PR TITLE
set SIGINIT-SIGTERM to actually stop the script

### PR DESCRIPTION
**Pull request by frankthetank7254**
I'm not sure if this is actually a good idea, as I was only just learning about traps in bash, but to me, it makes sense to actually stop the script when it receives a SIGINIT or SIGTERM instead of just deleting the temp file and letting it continue to run.

### CODE REVIEW

**Comment by feralhosting** [comment]
Would this achieve the same thing?

~~~
trap "rm -f $lock_file; exit 0" SIGINT SIGTERM
~~~

**Comment by feralhosting** [comment]
Did not mean to close.

**Comment by frankthetank7254** [comment]
sure. I guess I don't know why I felt the need to put it in a function.

Would you like me to submit a more simple pull request? Or will you make the change?

**Comment by feralhosting** [comment]
you can try just modifying the fork, it should update the pull request.

**Pull request closed without merging**
