### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by OsirisWsjr**
Edited SCGIpath to current correct path.

Port manual entry is unnecessary once SSL is checked.

Overview:
https://i.imgur.com/JDNEDsj_d.jpg

### CODE REVIEW

**Comment by userdocs** [comment]
That picture is really poor quality. Can you provide something better?

**Comment by OsirisWsjr** [comment]
Apologies, the _d (preview) should not of been included:  http://i.imgur.com/ojv5loU.jpg

**Comment by userdocs** [comment]
Why have you changed the rpc path?

This is the correct rpc path.

`/username/rtorrent/rpc`

**Comment by OsirisWsjr** [comment]
It's not rtorrent, it's rutorrent.
It's not rpc  it's  plugins/rpc/rpc.php

Try it and see.

**Comment by userdocs** [comment]
And where do you get this information from? The path is defined in an nginx conf file as the rpc should only work when you use nginx. Unless something has changed the guide should be in-line with how Feral installs these files and using nginx.

Tell me what is in your nginx conf files.

`/.nginx/conf.d/000-default-server.d`

Then look at this file:

`rpc.conf`

And you should see this on the first line: 

 `location /rtorrent/rpc {`

**Comment by OsirisWsjr** [comment]
Apologies this url is for Apache, not Nginx.    You don't have to switch to Nginx to use Transdroid.   I'll cancel and start a new pull request.

**Pull request closed without merging**
